# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 450c685958f8678cee74b590a36b066c13ba2661f6ea44ecc744e8a54233359e8ec8516f3e4f07142f023be1c2c4786034ccabf40faef7fb65ea1455e1a0a5fd

test:
  secret_key_base: cba9449e0ebc77a8f9e3d0b6b0ec71658ff666e34d83d0854c0ff4578e6f897e04d6cda5d095ae59baa8efbd8cfeae46fe83d2688d2588f50bcabbb98282fa18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
